### ISSUE TITLE
droping all eq on start

### ISSUE THREAD

**Issue by GrishaKosak** [UgurhanK/ThirdPerson-WIP#2]
Hello,

something weird is goin on my server.
after resp I droping all eq. Same when I buy something.

I using other plugins:
CS2-SimpleAdmin
K4-System
K4ryuuDamageInfo
RockTheVote
ServerGraphic
WeaponPaints

and secound, when I using !tp there is some error. Commands in console works, but no in chat.

![image](https://github.com/user-attachments/assets/5f9a4417-87ba-400d-bb7e-c55c808f8d8e)

![image](https://github.com/user-attachments/assets/cd7c9b54-4221-483f-a71f-80857b0f312a)
![image](https://github.com/user-attachments/assets/5d42bd8f-b21c-40dd-91aa-10bd586d25d4)

**Comment by grrhn** [comment]
This is about that plugins i think. Because my command not using args. One plugin has !tp command maybe.

**Comment by Wngui** [comment]
CS2-SimpleAdmin has a !tp command, probably that's the one interfering. 
The weapon drop seems odd, try "StripOnUse": false, in your config
